### PR TITLE
Add jasondavies/cloud

### PR DESCRIPTION
**Pull request by mwpastore**
cc @jasondavies

### CODE REVIEW

**Comment by ming-codes** [comment]
Hey! Thanks for the PR!

What's `vendor/jasondavies/cloud/index.js.patch`? This doesn't looks like it's needed.

**Comment by mwpastore** [comment]
You're welcome! It's the changes I had to make to index.js to get it to
work; the patch lets us quickly integrate upstream changes at a later date.
But I can certainly remove it and keep it elsewhere. Just let me know and
I'll update the PR.

**Comment by ming-codes** [comment]
I see. We can keep the patch file.

**Comment by ming-codes** [comment]
Published v3.2.0

**Pull request merged**
